Use HTTPS when fetching
eversport/node-unicodetable pull request #7
Opened 2017-04-14 23:31 UTC by thughes

See dodo/node-unicodetable#27 and https://nodesecurity.io/advisories/161

2017-04-16 14:29 UTC, tdanecker requested changes

2017-04-16 14:29 UTC, tdanecker commented on package.json
> +    "download": "curl \"https://unicode.org/Public/9.0.0/ucd/UnicodeData.txt\" > UnicodeData.txt",
have you tried the url? unfortunatly unicode.org doesn't support https :disappointed:

2017-04-17 18:10 UTC, thughes commented on package.json
> +    "download": "curl \"https://unicode.org/Public/9.0.0/ucd/UnicodeData.txt\" > UnicodeData.txt",
No, unfortunately the URL is blocked for me. I naively assumed a site like this would support HTTPS these days...

2017-04-24 09:35 UTC, tdanecker commented on package.json
> +    "download": "curl \"https://unicode.org/Public/9.0.0/ucd/UnicodeData.txt\" > UnicodeData.txt",
me too. I already wanted to approve the pr ;) thx for the contribution anyways, though!

2017-04-24 09:35 UTC, closed without merging

2017-08-22 00:42 UTC, alexframe commented
This is now supported over HTTPS, could this be merged?

https://unicode.org/Public/9.0.0/ucd/UnicodeData.txt

2017-09-01 05:14 UTC, alexframe commented
@tdanecker can we merge this now please?

It will resolve [node security platform advisory 161](https://nodesecurity.io/advisories/161)

2017-09-01 11:10 UTC, tdanecker commented
Hi,

I'm just back from holidays. The changes are merged now! Though the UnicodeData.txt isn't downloaded at installation-time anymore but only before the package is published. It didn't effect any users of the package, just the maintainers ;)

But thx for the hint anyways! It was about time that unicode.org supported https!

Cheers

2017-11-07 23:34 UTC, mrgordon commented
node projects still can't pass security scans because the latest `npm` includes `unicode` 6.3.0 which still has this http vulnerability. Any chance we can get this upgraded soon upstream? Not sure how much insight you have into which version of `unicode` they are building on

The exact dependency on this is via

`/usr/lib/node_modules/npm/node_modules/libnpx/node_modules/yargs/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/parse-json/vendor`

2017-11-07 23:35 UTC, mrgordon commented
Alternatively I was considering manually upgrading the version of `unicode` that is used. Is a changelog available anywhere? I'm trying to gauge how risky it is to go from 6.3.0 to 9.0.0 where the vulnerability is resolved.

2017-11-07 23:57 UTC, tdanecker commented
The new releases should be fully compatible with old versions.

Previously, the most recent data has been downloaded from unicode.org during install-time. Now the version-schema matches the unicode.org releases (which are published about once a year) and includes exactly that version of the data. But that's all that changed.

I would recommend to upgrade to the most recent version (10.0.0) for up-to-date unicode data.

For changes in the data, just have a look at the unicode.org release notes.